const assert = require('node:assert/strict');
const fs = require('node:fs');

const manifest = JSON.parse(fs.readFileSync('extension/manifest.json', 'utf8'));
const background = fs.readFileSync('extension/background.js', 'utf8');
const content = fs.readFileSync('extension/content/content.js', 'utf8');
const contentCss = fs.readFileSync('extension/content/content.css', 'utf8');
const sidepanel = fs.readFileSync('extension/sidepanel/sidepanel.js', 'utf8');
const sidepanelHtml = fs.readFileSync('extension/sidepanel/index.html', 'utf8');
const sidepanelCss = fs.readFileSync('extension/sidepanel/styles.css', 'utf8');

assert.ok(manifest.permissions.includes('sidePanel'), 'manifest must request sidePanel permission');
assert.ok(manifest.side_panel?.default_path === 'sidepanel/index.html', 'manifest must point to sidepanel/index.html');
assert.ok(!manifest.action?.default_popup, 'action popup would conflict with icon-triggered side panel behavior');
assert.match(background, /setPanelBehavior\(\{\s*openPanelOnActionClick:\s*true\s*\}/, 'background should enable openPanelOnActionClick');
assert.match(background, /chrome\.action\.onClicked\.addListener/, 'background should include action click fallback');
assert.match(background, /chrome\.sidePanel\.open/, 'background should open side panel from action click fallback');
assert.match(content, /miniPanelCollapsed:\s*false/, 'content settings should define mini panel collapse default');
assert.match(content, /shortcuts:\s*\{[\s\S]*select:\s*'a'[\s\S]*alternateSelect:\s*'s'[\s\S]*download:\s*'d'[\s\S]*newBatch:\s*'n'[\s\S]*clear:\s*'c'/, 'content settings should define default custom shortcut keys');
assert.match(content, /downloadLinks:\s*'1'[\s\S]*downloadDirect:\s*'2'[\s\S]*downloadZip:\s*'3'/, 'content settings should define default download mode shortcut keys');
assert.match(content, /idx-collapsed/, 'content should render collapsed mini panel state');
assert.match(content, /function imageContainingPoint/, 'content should fall back to coordinate-based image lookup for keyboard selection');
assert.match(content, /function selectPointedImage/, 'page dock shortcut should select the image under the pointer');
assert.match(content, /function shortcutKey/, 'content should resolve shortcut labels from settings');
assert.match(content, /function shortcutMatches/, 'content should compare pressed keys against custom shortcuts');
assert.match(content, /function shortcutValues/, 'content should derive repeat-guard keys from custom shortcuts');
assert.match(content, /function setupFloatingImage/, 'content should support body-level floating controls for fragile site-owned image containers');
assert.match(content, /adapter\.usesFloatingControls/, 'content should let site adapters opt into floating controls');
assert.match(content, /idx-floating-select-btn/, 'floating controls should use their own class for positioning and cleanup');
assert.match(content, /document\.hidden[\s\S]{0,180}setTimeout/, 'image scanning should fall back to setTimeout when requestAnimationFrame is throttled in background tabs');
assert.match(content, /style\.setProperty\('left'[\s\S]{0,80}'important'\)/, 'floating controls should override the base important left position');
assert.match(content, /style\.setProperty\('top'[\s\S]{0,80}'important'\)/, 'floating controls should override the base important top position');
assert.doesNotMatch(content, /function selectNextVisible/, 'page dock shortcut must not use ordered next-image selection');
assert.doesNotMatch(content, /function visibleImages/, 'shortcut selection should not walk ordered visible candidates');
assert.match(content, /data-shortcut="select"/, 'page dock should expose a dynamic select shortcut label');
assert.match(content, /data-shortcut="download"/, 'page dock should expose a dynamic download shortcut label');
assert.match(content, /data-shortcut="newBatch"/, 'page dock should expose a dynamic new-batch shortcut label');
assert.match(content, /function updateShortcutHints/, 'page dock should refresh shortcut labels when settings change');
assert.doesNotMatch(content, /全选<kbd>A<\/kbd>/, 'page dock must not present A as a bulk select action');
assert.doesNotMatch(content, /key === 'a'[\s\S]{0,120}selectVisible/, 'A key must not select every visible image');
assert.match(content, /shortcutMatches\('select'[\s\S]{0,160}selectPointedImage/, 'custom select shortcut should select the image under the pointer');
assert.match(content, /shortcutMatches\('alternateSelect'[\s\S]{0,120}selectPointedImage/, 'custom alternate select shortcut should select the image under the pointer');
assert.match(content, /event\.repeat[\s\S]{0,120}shortcutValues\(\)\.includes\(key\)/, 'shortcut auto-repeat should follow custom shortcut keys');
assert.match(content, /data-action="links"/, 'page dock should expose a links action');
assert.match(content, /data-action="prefix"/, 'page dock should expose a prefix action');
assert.match(content, /data-action="new-batch"/, 'page dock should expose a new batch action');
assert.match(content, /function showDownloadModal/, 'page dock download should open a mode chooser');
assert.match(content, /const DOWNLOAD_MODES = \[[\s\S]*mode:\s*'links'[\s\S]*shortcut:\s*'downloadLinks'[\s\S]*mode:\s*'direct'[\s\S]*shortcut:\s*'downloadDirect'[\s\S]*mode:\s*'zip'[\s\S]*shortcut:\s*'downloadZip'/, 'download modal should define mode shortcuts from one source');
assert.match(content, /function downloadModeButton/, 'download modal buttons should render from shared mode definitions');
assert.match(content, /function downloadModeForShortcut/, 'download modal should resolve keyboard shortcuts through a helper');
assert.match(content, /downloadModeForShortcut\(event\.key\)[\s\S]{0,220}runDownloadMode\(mode\)/, 'download modal shortcuts should trigger the resolved download mode');
assert.match(content, /function showPrefixModal/, 'page dock should support editing filename prefix inline');
assert.match(content, /function downloadResultMessage/, 'download completion should use an explicit result message');
assert.match(content, /ZIP 已保存/, 'zip completion toast should explicitly say the ZIP was saved');
assert.match(content, /clearSelected\(\{ silent: true \}\)/, 'download cleanup should not overwrite the success toast');
assert.match(content, /已选择 1 张图片/, 'single-image selection should report a one-image action');
assert.match(content, /class="idx-site-pill"/, 'page dock should show a compact site identity badge');
assert.match(content, /function siteTheme/, 'content script should resolve theme from the current site adapter');
assert.match(content, /adapter\.theme/, 'content script should use adapter theme instead of one global accent');
assert.doesNotMatch(content, /style\.setProperty\('--idx-accent', '#ff2442'\)/, 'page dock accent must not be hard-coded to one site color');
assert.match(content, /shortcutMatches\('newBatch'/, 'page dock should support a configurable new-batch shortcut');
assert.match(contentCss, /content:\s*"\\2713"/, 'active selection should render a checkmark escape');
assert.doesNotMatch(contentCss, /content:\s*"\\\\2713"/, 'active selection must not render literal 2713 text');
assert.match(contentCss, /--idx-accent-dark/, 'content CSS should expose a darker site accent for hover states');
assert.match(contentCss, /\.idx-site-pill/, 'page dock site badge should be styled');
assert.match(sidepanel, /miniPanelCollapsed:\s*false/, 'side panel settings should define mini panel collapse default');
assert.match(sidepanel, /shortcuts:\s*\{[\s\S]*select:\s*'a'[\s\S]*alternateSelect:\s*'s'[\s\S]*download:\s*'d'[\s\S]*newBatch:\s*'n'[\s\S]*clear:\s*'c'/, 'side panel settings should define default custom shortcut keys');
assert.match(sidepanel, /downloadLinks:\s*'1'[\s\S]*downloadDirect:\s*'2'[\s\S]*downloadZip:\s*'3'/, 'side panel settings should define default download mode shortcut keys');
assert.match(sidepanel, /mini-panel-collapsed/, 'side panel should expose mini panel collapse setting');
assert.match(sidepanelHtml, /id="shortcut-settings"/, 'settings should expose custom shortcut controls');
assert.match(sidepanelHtml, /data-shortcut-input="select"/, 'settings should allow editing select shortcut');
assert.match(sidepanelHtml, /data-shortcut-input="alternateSelect"/, 'settings should allow editing alternate select shortcut');
assert.match(sidepanelHtml, /data-shortcut-input="download"/, 'settings should allow editing download shortcut');
assert.match(sidepanelHtml, /data-shortcut-input="newBatch"/, 'settings should allow editing new-batch shortcut');
assert.match(sidepanelHtml, /data-shortcut-input="clear"/, 'settings should allow editing clear shortcut');
assert.match(sidepanelHtml, /data-shortcut-input="downloadLinks"/, 'settings should allow editing links download shortcut');
assert.match(sidepanelHtml, /data-shortcut-input="downloadDirect"/, 'settings should allow editing direct download shortcut');
assert.match(sidepanelHtml, /data-shortcut-input="downloadZip"/, 'settings should allow editing ZIP download shortcut');
assert.match(sidepanel, /function renderShortcutSettings/, 'side panel should render custom shortcut values');
assert.match(sidepanel, /function normalizeShortcutKey/, 'side panel should normalize user shortcut input');
assert.match(sidepanel, /function saveShortcut/, 'side panel should save custom shortcut changes');
assert.match(sidepanel, /function resetShortcuts/, 'side panel should reset shortcuts to defaults');
assert.match(sidepanelCss, /\.shortcut-grid/, 'custom shortcut controls should be styled');
assert.match(sidepanelCss, /\.shortcut-key/, 'shortcut key inputs should be styled');
assert.match(sidepanelHtml, /data-tab="history"[^>]*>历史</, 'side panel should expose a history tab');
assert.doesNotMatch(sidepanelHtml, /<h1>图拾 Dock<\/h1>/, 'side panel should not repeat the extension name in a visible top header');
assert.doesNotMatch(sidepanelHtml, /id="current-site"/, 'unsupported-page copy should not sit in a redundant top header');
assert.doesNotMatch(sidepanelHtml, /data-tab="donate"/, 'donation should not be a top-level tab');
assert.match(sidepanelHtml, /id="tab-settings"[\s\S]*打赏作者/, 'donation section should live inside settings tab');
assert.doesNotMatch(sidepanelHtml, /data-command=/, 'site tab should not expose duplicate page dock commands');
assert.doesNotMatch(sidepanelHtml, /download-row/, 'site tab should not expose duplicate download controls');
assert.doesNotMatch(sidepanelHtml, /support-qr-list/, 'settings should not render donation QR codes inline');
assert.match(sidepanelHtml, /data-donate="wechat"/, 'settings should expose WeChat donation option');
assert.match(sidepanelHtml, /data-donate="alipay"/, 'settings should expose Alipay donation option');
assert.match(sidepanelHtml, /data-donate="compute"/, 'settings should expose compute donation option');
assert.doesNotMatch(sidepanel, /bindCommands/, 'removed side panel commands should not be bound');
assert.doesNotMatch(sidepanel, /getElementById\('download-mode'\)/, 'removed side panel download mode control should not be referenced');
assert.doesNotMatch(sidepanelHtml, /id="download-mode"/, 'removed side panel download mode control should not exist');
assert.match(sidepanel, /function siteTheme/, 'side panel should resolve per-site theme metadata');
assert.match(sidepanel, /card\.style\.setProperty\('--site-accent'/, 'side panel site cards should receive their own accent color');
assert.match(sidepanel, /class="site-badge"/, 'side panel site cards should show compact site badges');
assert.match(sidepanel, /id:\s*'huaban'/, 'side panel should include Huaban in the supported site list');
assert.match(sidepanel, /host:\s*'huaban\.com'/, 'Huaban side panel card should show the supported host');
assert.match(sidepanel, /badge:\s*'花瓣'/, 'Huaban should use a compact site badge');
assert.match(sidepanel, /function showPanelModal/, 'side panel should use a shared modal function');
assert.match(sidepanel, /function showDonationModal/, 'donation options should open a modal');
assert.match(sidepanelHtml, /id="history-filter"/, 'history tab should expose a platform filter');
assert.match(sidepanel, /historyFilter/, 'side panel should track the selected history platform filter');
assert.match(sidepanel, /function renderHistoryFilter/, 'side panel should render platform filter chips');
assert.match(sidepanel, /function filteredHistoryItems/, 'history list should be filtered by selected platform');
assert.match(sidepanel, /--history-accent/, 'history records should receive platform accent colors');
assert.match(sidepanel, /function showHistoryModal/, 'history records should open a details modal');
assert.match(sidepanel, /function historyEntries/, 'history details should read stored image entries');
assert.match(sidepanel, /function renderHistoryPreview/, 'history details should render image/link previews');
assert.match(sidepanel, /function downloadHistoryItem/, 'history details should support re-downloading a record');
assert.match(sidepanelCss, /\.tab:not\(\.active\):not\(:disabled\):hover/, 'tabs should have a stable custom hover state');
assert.match(sidepanelCss, /\.site-badge/, 'side panel should style per-site badges');
assert.match(sidepanel, /class="site-toggle"/, 'site cards should expose an explicit expand/collapse button');
assert.match(sidepanel, /aria-expanded="\$\{expanded \? 'true' : 'false'\}"/, 'site card toggle should report expanded state');
assert.match(sidepanel, /展开设置/, 'collapsed site cards should clearly label the expand action');
assert.match(sidepanel, /收起设置/, 'expanded site cards should clearly label the collapse action');
assert.match(sidepanelCss, /grid-template-rows:\s*0fr/, 'site settings should collapse with grid rows');
assert.match(sidepanelCss, /\.site-card\.is-expanded \.site-settings[\s\S]*grid-template-rows:\s*1fr/, 'site settings should animate open with grid rows');
assert.match(sidepanelCss, /--current-accent/, 'side panel count should support current-site accent color');
assert.match(sidepanelCss, /\.history-filter/, 'history platform filter should be styled');
assert.match(sidepanelCss, /\.history-preview/, 'history preview grid should be styled');
assert.match(sidepanelCss, /\.history-download-actions/, 'history modal download actions should be styled');
assert.match(sidepanelCss, /\.panel-modal-backdrop/, 'side panel should define shared modal backdrop styles');
assert.match(sidepanelCss, /\.panel-modal-qr-frame/, 'donation modal should use shared QR framing styles');
assert.match(sidepanel, /downloadHistory/, 'side panel should read and render local history');

console.log('sidepanel trigger tests ok');
